FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Instalar dependencias adicionales para pruebas
RUN pip install pytest pytest-asyncio pytest-mock

CMD ["pytest"]
